// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFS(arg1) {
  return window['go']['main']['App']['BrowseFS'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function GeneratePreview(arg1, arg2) {
  return window['go']['main']['App']['GeneratePreview'](arg1, arg2);
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetLibraryStatus() {
  return window['go']['main']['App']['GetLibraryStatus']();
}

export function ListAlbums(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListAlbums'](arg1, arg2, arg3, arg4, arg5);
}

export function PublishAlbum(arg1, arg2) {
  return window['go']['main']['App']['PublishAlbum'](arg1, arg2);
}

export function ReloadLibrary(arg1) {
  return window['go']['main']['App']['ReloadLibrary'](arg1);
}
