// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function BrowseFS(arg1:string):Promise<any>;

export function ClearCache():Promise<any>;

export function GeneratePreview(arg1:string,arg2:boolean):Promise<any>;

export function GetAlbum(arg1:string):Promise<any>;

export function GetLibraryStatus():Promise<any>;

export function ListAlbums(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<any>;

export function PublishAlbum(arg1:string,arg2:boolean):Promise<any>;

export function ReloadLibrary(arg1:api.ReloadRequest):Promise<any>;
